Repository CosmoStat/shapepipe, pull requests merged in 2022-10, with the labels that each got.

#586 Bug fix(es) for v1.0.1
  docs/source/installation.md
  example/cfis/config_make_cat_mccd.ini
  example/cfis/config_tile_MiViSmVi.ini
  shapepipe/modules/mask_package/mask.py
Labels: bug fix

#589 Patch fixes for v1.0.1
  docs/source/installation.md
  example/cfis/config_Rc.ini
  example/cfis/config_make_cat_mccd.ini
  example/cfis/config_tile_MiViSmVi.ini
  shapepipe/modules/mask_package/mask.py
  shapepipe/modules/random_cat_package/__init__.py
  shapepipe/modules/random_cat_package/random_cat.py
  shapepipe/modules/random_cat_runner.py
Labels: release

#592 Hsc stars
  scripts/jupyter/plot_spectro_areas.ipynb
Labels: enhancement
