Repository CosmoStat/shapepipe, pull requests merged in 2022-03, with the labels that each got.

#542 Test CD
  .github/workflows/cd.yml
Labels: tests

#548 fixed bug in RunLog class
  shapepipe/pipeline/run_log.py
Labels: bug fix

#550 added contribution guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.rst
Labels: documentation

#552 tutorial bugfixes
  example/cfis/config_make_cat_mccd.ini
  example/cfis/config_make_cat_psfex.ini
  example/cfis/config_tile_MiViSmVi.ini
  example/cfis/config_tile_Ng_template.ini
  example/cfis/config_tile_PiViSmVi.ini
  example/cfis/config_tile_Sx_exp_mccd.ini
  example/cfis/config_tile_Sx_exp_psfex.ini
  shapepipe/modules/ngmix_package/ngmix.py
Labels: bug

#554 Removed pep8 error exceptions
  setup.cfg
  shapepipe/modules/mccd_package/__init__.py
  shapepipe/modules/mccd_package/mccd_plot_utilities.py
  shapepipe/modules/setools_package/__init__.py
Labels: clean up

#553 Understanding the API docs
  docs/source/about.md
  docs/source/basic_execution.md
  docs/source/conf.py
  docs/source/configuration.md
  docs/source/contributing.md
  docs/source/installation.md
  docs/source/module_develop.md
  docs/source/module_example.md
  docs/source/toc.rst
  docs/source/understanding_api.md
Labels: documentation
