Repository CosmoStat/shapepipe, pull requests merged in 2023-06, with the labels that each got.

#628 Corrected documentation: module names in module sections
  shapepipe/modules/mccd_interp_runner.py
  shapepipe/modules/mccd_package/__init__.py
  shapepipe/modules/psfex_interp_package/__init__.py
  shapepipe/modules/vignetmaker_package/__init__.py
Labels: documentation

#613 updated CI set up
  .github/workflows/ci-tests.yml
Labels: clean up

#623 mccd runner: DEC -> DES for rho stats mode
  shapepipe/modules/mccd_plots_runner.py
Labels: bug fix
